# -*- coding: utf-8 -*-
"""RBL_MODEL TRAINING-SEM-7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cH4kFbenHLPBsY1oPfNixnueENjN7pR0
"""

import pandas as pd

# Load the dataset (replace 'your_dataset.csv' with your actual filename)
df = pd.read_csv('/content/RBL1_data.csv')
print(df.head())  # Display the first few rows of the dataset

print(df.info())  # Get information about data types and non-null counts
print(df.describe())  # Get summary statistics for numerical columns

df.fillna(method='ffill', inplace=True)  # Forward fill for missing values

from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
df[['PLETH']] = scaler.fit_transform(df[['PLETH']])

X = df[['PLETH', 'HR', 'PULSE']]  # Features: PLETH, HR, PULSE
y = df['SpO2']  # Target: SpO2 values

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

import tensorflow as tf
from tensorflow.keras import layers, models

# Reshape input for CNN (if using 1D CNN)
X_train_cnn = X_train.values.reshape(-1, X_train.shape[1], 1)
X_test_cnn = X_test.values.reshape(-1, X_test.shape[1], 1)

# Define CNN model architecture
model_cnn = models.Sequential()
model_cnn.add(layers.Conv1D(64, kernel_size=3, activation='relu', input_shape=(X_train_cnn.shape[1], 1)))
# Remove the MaxPooling1D layer or decrease the pool_size to 1
#model_cnn.add(layers.MaxPooling1D(pool_size=2))
model_cnn.add(layers.MaxPooling1D(pool_size=1))
model_cnn.add(layers.Flatten())
model_cnn.add(layers.Dense(256, activation='relu'))
model_cnn.add(layers.Dense(1))  # Output layer for regression

# Compile model
model_cnn.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.001), loss='mean_squared_error')

# Train CNN model
model_cnn.fit(X_train_cnn, y_train, validation_data=(X_test_cnn, y_test), epochs=100, batch_size=32)

from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.gaussian_process.kernels import RBF, ConstantKernel as C

# Define kernel for GPR
kernel = C(1.0) * RBF(length_scale=1.0)

# Create Gaussian Process model
gpr = GaussianProcessRegressor(kernel=kernel)

# Fit GPR model on training data
gpr.fit(X_train, y_train)

# Predictions using CNN Model
y_pred_cnn = model_cnn.predict(X_test_cnn)

# Predictions using GPR Model
y_pred_gpr = gpr.predict(X_test)

# Calculate performance metrics for both models
from sklearn.metrics import mean_absolute_error, mean_squared_error

mae_cnn = mean_absolute_error(y_test, y_pred_cnn)
rmse_cnn = mean_squared_error(y_test, y_pred_cnn, squared=False)

mae_gpr = mean_absolute_error(y_test, y_pred_gpr)
rmse_gpr = mean_squared_error(y_test, y_pred_gpr, squared=False)

print(f"CNN MAE: {mae_cnn}, RMSE: {rmse_cnn}")
print(f"GPR MAE: {mae_gpr}, RMSE: {rmse_gpr}")

import matplotlib.pyplot as plt

# Scatter plot for CNN predictions
plt.figure(figsize=(12, 6))

# Plot for CNN predictions
plt.subplot(1, 2, 1)
plt.scatter(y_test, y_pred_cnn, color='blue', alpha=0.6)
plt.plot([min(y_test), max(y_test)], [min(y_test), max(y_test)], color='red', linestyle='--')  # Diagonal line for reference
plt.xlabel('Actual SpO2')
plt.ylabel('Predicted SpO2')
plt.title('CNN Predictions')
plt.grid()

# Plot for GPR predictions
plt.subplot(1, 2, 2)
plt.scatter(y_test, y_pred_gpr, color='green', alpha=0.6)
plt.plot([min(y_test), max(y_test)], [min(y_test), max(y_test)], color='red', linestyle='--')  # Diagonal line for reference
plt.xlabel('Actual SpO2')
plt.ylabel('Predicted SpO2')
plt.title('GPR Predictions')
plt.grid()

plt.tight_layout()
plt.show()

# Save CNN Model
model_cnn.save('cnn_model.h5')

# Save GPR Model (using joblib)
import joblib

joblib.dump(gpr, 'gpr_model.pkl')

print("Models saved successfully.")

"""# **TESTINGGG**"""

import pandas as pd

# Load the new data (replace 'new_data.csv' with your actual filename)
new_data = pd.read_csv('/content/Test (3).csv')
print(new_data.head())  # Display the first few rows of the new dataset

new_data.fillna(method='ffill', inplace=True)  # Forward fill for missing values

# Import the necessary library and class
from sklearn.preprocessing import MinMaxScaler

# Assuming you have fitted a scaler during training
scaler = MinMaxScaler()

# Check for string values in the 'PLETH' column and try converting them
# Assuming your data should be numeric, try to handle non-numeric values by setting them to NaN
new_data['PLETH'] = pd.to_numeric(new_data['PLETH'], errors='coerce')

# Access the 'PLETH' column data correctly
pleth_data = new_data['PLETH'].values.astype(float).reshape(-1, 1)

# Normalize PLETH signal (fit only if you are using a new scaler)
new_data['PLETH'] = scaler.fit_transform(pleth_data)  # Normalize PLETH signal

X_new = new_data[['PLETH', 'HR', 'PULSE']]
X_new_cnn = X_new.values.reshape(-1, X_new.shape[1], 1)  # Reshape for CNN input

# Import the TensorFlow library
import tensorflow as tf

# Load the trained CNN model (if you saved it previously)
model_cnn = tf.keras.models.load_model('cnn_model.h5')

# Make predictions on the new data
predictions_cnn = model_cnn.predict(X_new_cnn)

# Optionally, add predictions to your DataFrame
new_data['Predicted_SpO2'] = predictions_cnn

new_data.to_csv('predictions.csv', index=False)  # Save predictions to a CSV file
print("Predictions saved successfully.")